/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingTermsOfServiceRouteImport } from './routes/_landing/terms-of-service'
import { Route as LandingServicesRouteImport } from './routes/_landing/services'
import { Route as LandingPrivacyPolicyRouteImport } from './routes/_landing/privacy-policy'
import { Route as LandingGalleryRouteImport } from './routes/_landing/gallery'
import { Route as LandingContactRouteImport } from './routes/_landing/contact'
import { Route as LandingCareerRouteImport } from './routes/_landing/career'
import { Route as LandingArticlesRouteImport } from './routes/_landing/articles'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'
import { Route as DashboardVacanciesIndexRouteImport } from './routes/dashboard/vacancies/index'
import { Route as DashboardServicesIndexRouteImport } from './routes/dashboard/services/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardGalleryIndexRouteImport } from './routes/dashboard/gallery/index'
import { Route as DashboardBusinessSectorsIndexRouteImport } from './routes/dashboard/business-sectors/index'
import { Route as DashboardBlogsIndexRouteImport } from './routes/dashboard/blogs/index'
import { Route as DashboardServicesCreateRouteImport } from './routes/dashboard/services/create'
import { Route as DashboardGalleryCategoriesRouteImport } from './routes/dashboard/gallery/categories'
import { Route as DashboardBusinessSectorsCreateRouteImport } from './routes/dashboard/business-sectors/create'
import { Route as LandingServicesSlugRouteImport } from './routes/_landing/services.$slug'
import { Route as LandingSectorsSlugRouteImport } from './routes/_landing/sectors.$slug'
import { Route as LandingCareerSlugRouteImport } from './routes/_landing/career.$slug'
import { Route as LandingArticlesSlugRouteImport } from './routes/_landing/articles.$slug'
import { Route as DashboardVacanciesSlugIndexRouteImport } from './routes/dashboard/vacancies/$slug/index'
import { Route as DashboardUserManagementUserIdIndexRouteImport } from './routes/dashboard/user-management/$userId/index'
import { Route as DashboardTestimonialsIdIndexRouteImport } from './routes/dashboard/testimonials/$id/index'
import { Route as DashboardServicesSlugIndexRouteImport } from './routes/dashboard/services/$slug/index'
import { Route as DashboardProductsSlugIndexRouteImport } from './routes/dashboard/products/$slug/index'
import { Route as DashboardPartnersIdIndexRouteImport } from './routes/dashboard/partners/$id/index'
import { Route as DashboardGalleryIdIndexRouteImport } from './routes/dashboard/gallery/$id/index'
import { Route as DashboardContactUsIdIndexRouteImport } from './routes/dashboard/contact-us/$id/index'
import { Route as DashboardClientProjectsSlugIndexRouteImport } from './routes/dashboard/client-projects/$slug/index'
import { Route as DashboardBusinessSectorsSlugIndexRouteImport } from './routes/dashboard/business-sectors/$slug/index'
import { Route as DashboardBlogsSlugIndexRouteImport } from './routes/dashboard/blogs/$slug/index'
import { Route as DashboardAchievementsIdIndexRouteImport } from './routes/dashboard/achievements/$id/index'
import { Route as DashboardVacanciesSlugEditRouteImport } from './routes/dashboard/vacancies/$slug/edit'
import { Route as DashboardVacanciesSlugApplicationsRouteImport } from './routes/dashboard/vacancies/$slug/applications'
import { Route as DashboardUserManagementUserIdEditRouteImport } from './routes/dashboard/user-management/$userId/edit'
import { Route as DashboardTestimonialsIdEditRouteImport } from './routes/dashboard/testimonials/$id/edit'
import { Route as DashboardServicesSlugEditRouteImport } from './routes/dashboard/services/$slug/edit'
import { Route as DashboardProductsSlugEditRouteImport } from './routes/dashboard/products/$slug/edit'
import { Route as DashboardPartnersIdEditRouteImport } from './routes/dashboard/partners/$id/edit'
import { Route as DashboardGalleryIdEditRouteImport } from './routes/dashboard/gallery/$id/edit'
import { Route as DashboardContactUsIdEditRouteImport } from './routes/dashboard/contact-us/$id/edit'
import { Route as DashboardClientProjectsSlugEditRouteImport } from './routes/dashboard/client-projects/$slug/edit'
import { Route as DashboardBusinessSectorsSlugEditRouteImport } from './routes/dashboard/business-sectors/$slug/edit'
import { Route as DashboardBlogsSlugEditRouteImport } from './routes/dashboard/blogs/$slug/edit'
import { Route as DashboardAchievementsIdEditRouteImport } from './routes/dashboard/achievements/$id/edit'

const RegisterLazyRouteImport = createFileRoute('/register')()
const RateLimitLazyRouteImport = createFileRoute('/rate-limit')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ForbiddenLazyRouteImport = createFileRoute('/forbidden')()
const DashboardUserManagementIndexLazyRouteImport = createFileRoute(
  '/dashboard/user-management/',
)()
const DashboardTestimonialsIndexLazyRouteImport = createFileRoute(
  '/dashboard/testimonials/',
)()
const DashboardTagsIndexLazyRouteImport = createFileRoute('/dashboard/tags/')()
const DashboardSocialsIndexLazyRouteImport = createFileRoute(
  '/dashboard/socials/',
)()
const DashboardPartnersIndexLazyRouteImport = createFileRoute(
  '/dashboard/partners/',
)()
const DashboardOrganizationalStructureIndexLazyRouteImport = createFileRoute(
  '/dashboard/organizational-structure/',
)()
const DashboardNewsletterIndexLazyRouteImport = createFileRoute(
  '/dashboard/newsletter/',
)()
const DashboardFaqsIndexLazyRouteImport = createFileRoute('/dashboard/faqs/')()
const DashboardContactUsIndexLazyRouteImport = createFileRoute(
  '/dashboard/contact-us/',
)()
const DashboardClientProjectsIndexLazyRouteImport = createFileRoute(
  '/dashboard/client-projects/',
)()
const DashboardAchievementsIndexLazyRouteImport = createFileRoute(
  '/dashboard/achievements/',
)()
const DashboardVacanciesCreateLazyRouteImport = createFileRoute(
  '/dashboard/vacancies/create',
)()
const DashboardUserManagementCreateLazyRouteImport = createFileRoute(
  '/dashboard/user-management/create',
)()
const DashboardTestimonialsCreateLazyRouteImport = createFileRoute(
  '/dashboard/testimonials/create',
)()
const DashboardProductsCreateLazyRouteImport = createFileRoute(
  '/dashboard/products/create',
)()
const DashboardPartnersCreateLazyRouteImport = createFileRoute(
  '/dashboard/partners/create',
)()
const DashboardGalleryCreateLazyRouteImport = createFileRoute(
  '/dashboard/gallery/create',
)()
const DashboardContactUsCreateLazyRouteImport = createFileRoute(
  '/dashboard/contact-us/create',
)()
const DashboardClientProjectsCreateLazyRouteImport = createFileRoute(
  '/dashboard/client-projects/create',
)()
const DashboardBlogsCreateLazyRouteImport = createFileRoute(
  '/dashboard/blogs/create',
)()
const DashboardAchievementsCreateLazyRouteImport = createFileRoute(
  '/dashboard/achievements/create',
)()

const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const RateLimitLazyRoute = RateLimitLazyRouteImport.update({
  id: '/rate-limit',
  path: '/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/rate-limit.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForbiddenLazyRoute = ForbiddenLazyRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/forbidden.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingTermsOfServiceRoute = LandingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LandingRoute,
} as any)
const LandingServicesRoute = LandingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyPolicyRoute = LandingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LandingRoute,
} as any)
const LandingGalleryRoute = LandingGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LandingRoute,
} as any)
const LandingContactRoute = LandingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LandingRoute,
} as any)
const LandingCareerRoute = LandingCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => LandingRoute,
} as any)
const LandingArticlesRoute = LandingArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardUserManagementIndexLazyRoute =
  DashboardUserManagementIndexLazyRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIndexLazyRoute =
  DashboardTestimonialsIndexLazyRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/index.lazy').then((d) => d.Route),
  )
const DashboardTagsIndexLazyRoute = DashboardTagsIndexLazyRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/tags/index.lazy').then((d) => d.Route),
)
const DashboardSocialsIndexLazyRoute =
  DashboardSocialsIndexLazyRouteImport.update({
    id: '/socials/',
    path: '/socials/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/socials/index.lazy').then((d) => d.Route),
  )
const DashboardPartnersIndexLazyRoute =
  DashboardPartnersIndexLazyRouteImport.update({
    id: '/partners/',
    path: '/partners/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/index.lazy').then((d) => d.Route),
  )
const DashboardOrganizationalStructureIndexLazyRoute =
  DashboardOrganizationalStructureIndexLazyRouteImport.update({
    id: '/organizational-structure/',
    path: '/organizational-structure/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/organizational-structure/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardNewsletterIndexLazyRoute =
  DashboardNewsletterIndexLazyRouteImport.update({
    id: '/newsletter/',
    path: '/newsletter/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/newsletter/index.lazy').then((d) => d.Route),
  )
const DashboardFaqsIndexLazyRoute = DashboardFaqsIndexLazyRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/faqs/index.lazy').then((d) => d.Route),
)
const DashboardContactUsIndexLazyRoute =
  DashboardContactUsIndexLazyRouteImport.update({
    id: '/contact-us/',
    path: '/contact-us/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/index.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsIndexLazyRoute =
  DashboardClientProjectsIndexLazyRouteImport.update({
    id: '/client-projects/',
    path: '/client-projects/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardAchievementsIndexLazyRoute =
  DashboardAchievementsIndexLazyRouteImport.update({
    id: '/achievements/',
    path: '/achievements/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/achievements/index.lazy').then((d) => d.Route),
  )
const DashboardVacanciesIndexRoute = DashboardVacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/vacancies/index.lazy').then((d) => d.Route),
)
const DashboardServicesIndexRoute = DashboardServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/services/index.lazy').then((d) => d.Route),
)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/products/index.lazy').then((d) => d.Route),
)
const DashboardGalleryIndexRoute = DashboardGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/index.lazy').then((d) => d.Route),
)
const DashboardBusinessSectorsIndexRoute =
  DashboardBusinessSectorsIndexRouteImport.update({
    id: '/business-sectors/',
    path: '/business-sectors/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsIndexRoute = DashboardBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/index.lazy').then((d) => d.Route),
)
const DashboardVacanciesCreateLazyRoute =
  DashboardVacanciesCreateLazyRouteImport.update({
    id: '/vacancies/create',
    path: '/vacancies/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/create.lazy').then((d) => d.Route),
  )
const DashboardUserManagementCreateLazyRoute =
  DashboardUserManagementCreateLazyRouteImport.update({
    id: '/user-management/create',
    path: '/user-management/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsCreateLazyRoute =
  DashboardTestimonialsCreateLazyRouteImport.update({
    id: '/testimonials/create',
    path: '/testimonials/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/create.lazy').then((d) => d.Route),
  )
const DashboardProductsCreateLazyRoute =
  DashboardProductsCreateLazyRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/create.lazy').then((d) => d.Route),
  )
const DashboardPartnersCreateLazyRoute =
  DashboardPartnersCreateLazyRouteImport.update({
    id: '/partners/create',
    path: '/partners/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/create.lazy').then((d) => d.Route),
  )
const DashboardGalleryCreateLazyRoute =
  DashboardGalleryCreateLazyRouteImport.update({
    id: '/gallery/create',
    path: '/gallery/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/gallery/create.lazy').then((d) => d.Route),
  )
const DashboardContactUsCreateLazyRoute =
  DashboardContactUsCreateLazyRouteImport.update({
    id: '/contact-us/create',
    path: '/contact-us/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/create.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsCreateLazyRoute =
  DashboardClientProjectsCreateLazyRouteImport.update({
    id: '/client-projects/create',
    path: '/client-projects/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsCreateLazyRoute =
  DashboardBlogsCreateLazyRouteImport.update({
    id: '/blogs/create',
    path: '/blogs/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/blogs/create.lazy').then((d) => d.Route),
  )
const DashboardAchievementsCreateLazyRoute =
  DashboardAchievementsCreateLazyRouteImport.update({
    id: '/achievements/create',
    path: '/achievements/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/achievements/create.lazy').then((d) => d.Route),
  )
const DashboardServicesCreateRoute = DashboardServicesCreateRouteImport.update({
  id: '/services/create',
  path: '/services/create',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/services/create.lazy').then((d) => d.Route),
)
const DashboardGalleryCategoriesRoute =
  DashboardGalleryCategoriesRouteImport.update({
    id: '/gallery/categories',
    path: '/gallery/categories',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/gallery/categories.lazy').then((d) => d.Route),
  )
const DashboardBusinessSectorsCreateRoute =
  DashboardBusinessSectorsCreateRouteImport.update({
    id: '/business-sectors/create',
    path: '/business-sectors/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/create.lazy').then(
      (d) => d.Route,
    ),
  )
const LandingServicesSlugRoute = LandingServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LandingServicesRoute,
} as any)
const LandingSectorsSlugRoute = LandingSectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => LandingRoute,
} as any)
const LandingCareerSlugRoute = LandingCareerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LandingCareerRoute,
} as any)
const LandingArticlesSlugRoute = LandingArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LandingArticlesRoute,
} as any)
const DashboardVacanciesSlugIndexRoute =
  DashboardVacanciesSlugIndexRouteImport.update({
    id: '/vacancies/$slug/',
    path: '/vacancies/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardUserManagementUserIdIndexRoute =
  DashboardUserManagementUserIdIndexRouteImport.update({
    id: '/user-management/$userId/',
    path: '/user-management/$userId/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/$userId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIdIndexRoute =
  DashboardTestimonialsIdIndexRouteImport.update({
    id: '/testimonials/$id/',
    path: '/testimonials/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardServicesSlugIndexRoute =
  DashboardServicesSlugIndexRouteImport.update({
    id: '/services/$slug/',
    path: '/services/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/services/$slug/index.lazy').then((d) => d.Route),
  )
const DashboardProductsSlugIndexRoute =
  DashboardProductsSlugIndexRouteImport.update({
    id: '/products/$slug/',
    path: '/products/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/$slug/index.lazy').then((d) => d.Route),
  )
const DashboardPartnersIdIndexRoute =
  DashboardPartnersIdIndexRouteImport.update({
    id: '/partners/$id/',
    path: '/partners/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/$id/index.lazy').then((d) => d.Route),
  )
const DashboardGalleryIdIndexRoute = DashboardGalleryIdIndexRouteImport.update({
  id: '/gallery/$id/',
  path: '/gallery/$id/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/$id/index.lazy').then((d) => d.Route),
)
const DashboardContactUsIdIndexRoute =
  DashboardContactUsIdIndexRouteImport.update({
    id: '/contact-us/$id/',
    path: '/contact-us/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/$id/index.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsSlugIndexRoute =
  DashboardClientProjectsSlugIndexRouteImport.update({
    id: '/client-projects/$slug/',
    path: '/client-projects/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBusinessSectorsSlugIndexRoute =
  DashboardBusinessSectorsSlugIndexRouteImport.update({
    id: '/business-sectors/$slug/',
    path: '/business-sectors/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsSlugIndexRoute = DashboardBlogsSlugIndexRouteImport.update({
  id: '/blogs/$slug/',
  path: '/blogs/$slug/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/$slug/index.lazy').then((d) => d.Route),
)
const DashboardAchievementsIdIndexRoute =
  DashboardAchievementsIdIndexRouteImport.update({
    id: '/achievements/$id/',
    path: '/achievements/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/achievements/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardVacanciesSlugEditRoute =
  DashboardVacanciesSlugEditRouteImport.update({
    id: '/vacancies/$slug/edit',
    path: '/vacancies/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardVacanciesSlugApplicationsRoute =
  DashboardVacanciesSlugApplicationsRouteImport.update({
    id: '/vacancies/$slug/applications',
    path: '/vacancies/$slug/applications',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/applications.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardUserManagementUserIdEditRoute =
  DashboardUserManagementUserIdEditRouteImport.update({
    id: '/user-management/$userId/edit',
    path: '/user-management/$userId/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/$userId/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIdEditRoute =
  DashboardTestimonialsIdEditRouteImport.update({
    id: '/testimonials/$id/edit',
    path: '/testimonials/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardServicesSlugEditRoute =
  DashboardServicesSlugEditRouteImport.update({
    id: '/services/$slug/edit',
    path: '/services/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/services/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardProductsSlugEditRoute =
  DashboardProductsSlugEditRouteImport.update({
    id: '/products/$slug/edit',
    path: '/products/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardPartnersIdEditRoute = DashboardPartnersIdEditRouteImport.update({
  id: '/partners/$id/edit',
  path: '/partners/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/partners/$id/edit.lazy').then((d) => d.Route),
)
const DashboardGalleryIdEditRoute = DashboardGalleryIdEditRouteImport.update({
  id: '/gallery/$id/edit',
  path: '/gallery/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/$id/edit.lazy').then((d) => d.Route),
)
const DashboardContactUsIdEditRoute =
  DashboardContactUsIdEditRouteImport.update({
    id: '/contact-us/$id/edit',
    path: '/contact-us/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/$id/edit.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsSlugEditRoute =
  DashboardClientProjectsSlugEditRouteImport.update({
    id: '/client-projects/$slug/edit',
    path: '/client-projects/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/$slug/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBusinessSectorsSlugEditRoute =
  DashboardBusinessSectorsSlugEditRouteImport.update({
    id: '/business-sectors/$slug/edit',
    path: '/business-sectors/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/$slug/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsSlugEditRoute = DashboardBlogsSlugEditRouteImport.update({
  id: '/blogs/$slug/edit',
  path: '/blogs/$slug/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/$slug/edit.lazy').then((d) => d.Route),
)
const DashboardAchievementsIdEditRoute =
  DashboardAchievementsIdEditRouteImport.update({
    id: '/achievements/$id/edit',
    path: '/achievements/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/achievements/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/about': typeof LandingAboutRoute
  '/articles': typeof LandingArticlesRouteWithChildren
  '/career': typeof LandingCareerRouteWithChildren
  '/contact': typeof LandingContactRoute
  '/gallery': typeof LandingGalleryRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/services': typeof LandingServicesRouteWithChildren
  '/terms-of-service': typeof LandingTermsOfServiceRoute
  '/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/articles/$slug': typeof LandingArticlesSlugRoute
  '/career/$slug': typeof LandingCareerSlugRoute
  '/sectors/$slug': typeof LandingSectorsSlugRoute
  '/services/$slug': typeof LandingServicesSlugRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/dashboard/achievements/create': typeof DashboardAchievementsCreateLazyRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery': typeof DashboardGalleryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies': typeof DashboardVacanciesIndexRoute
  '/dashboard/achievements': typeof DashboardAchievementsIndexLazyRoute
  '/dashboard/client-projects': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/newsletter': typeof DashboardNewsletterIndexLazyRoute
  '/dashboard/organizational-structure': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/achievements/$id/edit': typeof DashboardAchievementsIdEditRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/achievements/$id': typeof DashboardAchievementsIdIndexRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/about': typeof LandingAboutRoute
  '/articles': typeof LandingArticlesRouteWithChildren
  '/career': typeof LandingCareerRouteWithChildren
  '/contact': typeof LandingContactRoute
  '/gallery': typeof LandingGalleryRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/services': typeof LandingServicesRouteWithChildren
  '/terms-of-service': typeof LandingTermsOfServiceRoute
  '/': typeof LandingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/articles/$slug': typeof LandingArticlesSlugRoute
  '/career/$slug': typeof LandingCareerSlugRoute
  '/sectors/$slug': typeof LandingSectorsSlugRoute
  '/services/$slug': typeof LandingServicesSlugRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/dashboard/achievements/create': typeof DashboardAchievementsCreateLazyRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery': typeof DashboardGalleryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies': typeof DashboardVacanciesIndexRoute
  '/dashboard/achievements': typeof DashboardAchievementsIndexLazyRoute
  '/dashboard/client-projects': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/newsletter': typeof DashboardNewsletterIndexLazyRoute
  '/dashboard/organizational-structure': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/achievements/$id/edit': typeof DashboardAchievementsIdEditRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/achievements/$id': typeof DashboardAchievementsIdIndexRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/_landing/about': typeof LandingAboutRoute
  '/_landing/articles': typeof LandingArticlesRouteWithChildren
  '/_landing/career': typeof LandingCareerRouteWithChildren
  '/_landing/contact': typeof LandingContactRoute
  '/_landing/gallery': typeof LandingGalleryRoute
  '/_landing/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/_landing/services': typeof LandingServicesRouteWithChildren
  '/_landing/terms-of-service': typeof LandingTermsOfServiceRoute
  '/_landing/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_landing/articles/$slug': typeof LandingArticlesSlugRoute
  '/_landing/career/$slug': typeof LandingCareerSlugRoute
  '/_landing/sectors/$slug': typeof LandingSectorsSlugRoute
  '/_landing/services/$slug': typeof LandingServicesSlugRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/dashboard/achievements/create': typeof DashboardAchievementsCreateLazyRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/dashboard/blogs/': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors/': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery/': typeof DashboardGalleryIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies/': typeof DashboardVacanciesIndexRoute
  '/dashboard/achievements/': typeof DashboardAchievementsIndexLazyRoute
  '/dashboard/client-projects/': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us/': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs/': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/newsletter/': typeof DashboardNewsletterIndexLazyRoute
  '/dashboard/organizational-structure/': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners/': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials/': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags/': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials/': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management/': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/achievements/$id/edit': typeof DashboardAchievementsIdEditRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/achievements/$id/': typeof DashboardAchievementsIdIndexRoute
  '/dashboard/blogs/$slug/': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug/': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug/': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id/': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id/': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id/': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug/': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug/': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id/': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId/': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug/': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/about'
    | '/articles'
    | '/career'
    | '/contact'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-service'
    | '/'
    | '/dashboard/'
    | '/articles/$slug'
    | '/career/$slug'
    | '/sectors/$slug'
    | '/services/$slug'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/dashboard/achievements/create'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/dashboard/blogs'
    | '/dashboard/business-sectors'
    | '/dashboard/gallery'
    | '/dashboard/products'
    | '/dashboard/services'
    | '/dashboard/vacancies'
    | '/dashboard/achievements'
    | '/dashboard/client-projects'
    | '/dashboard/contact-us'
    | '/dashboard/faqs'
    | '/dashboard/newsletter'
    | '/dashboard/organizational-structure'
    | '/dashboard/partners'
    | '/dashboard/socials'
    | '/dashboard/tags'
    | '/dashboard/testimonials'
    | '/dashboard/user-management'
    | '/dashboard/achievements/$id/edit'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/achievements/$id'
    | '/dashboard/blogs/$slug'
    | '/dashboard/business-sectors/$slug'
    | '/dashboard/client-projects/$slug'
    | '/dashboard/contact-us/$id'
    | '/dashboard/gallery/$id'
    | '/dashboard/partners/$id'
    | '/dashboard/products/$slug'
    | '/dashboard/services/$slug'
    | '/dashboard/testimonials/$id'
    | '/dashboard/user-management/$userId'
    | '/dashboard/vacancies/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/about'
    | '/articles'
    | '/career'
    | '/contact'
    | '/gallery'
    | '/privacy-policy'
    | '/services'
    | '/terms-of-service'
    | '/'
    | '/dashboard'
    | '/articles/$slug'
    | '/career/$slug'
    | '/sectors/$slug'
    | '/services/$slug'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/dashboard/achievements/create'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/dashboard/blogs'
    | '/dashboard/business-sectors'
    | '/dashboard/gallery'
    | '/dashboard/products'
    | '/dashboard/services'
    | '/dashboard/vacancies'
    | '/dashboard/achievements'
    | '/dashboard/client-projects'
    | '/dashboard/contact-us'
    | '/dashboard/faqs'
    | '/dashboard/newsletter'
    | '/dashboard/organizational-structure'
    | '/dashboard/partners'
    | '/dashboard/socials'
    | '/dashboard/tags'
    | '/dashboard/testimonials'
    | '/dashboard/user-management'
    | '/dashboard/achievements/$id/edit'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/achievements/$id'
    | '/dashboard/blogs/$slug'
    | '/dashboard/business-sectors/$slug'
    | '/dashboard/client-projects/$slug'
    | '/dashboard/contact-us/$id'
    | '/dashboard/gallery/$id'
    | '/dashboard/partners/$id'
    | '/dashboard/products/$slug'
    | '/dashboard/services/$slug'
    | '/dashboard/testimonials/$id'
    | '/dashboard/user-management/$userId'
    | '/dashboard/vacancies/$slug'
  id:
    | '__root__'
    | '/_landing'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/_landing/about'
    | '/_landing/articles'
    | '/_landing/career'
    | '/_landing/contact'
    | '/_landing/gallery'
    | '/_landing/privacy-policy'
    | '/_landing/services'
    | '/_landing/terms-of-service'
    | '/_landing/'
    | '/dashboard/'
    | '/_landing/articles/$slug'
    | '/_landing/career/$slug'
    | '/_landing/sectors/$slug'
    | '/_landing/services/$slug'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/dashboard/achievements/create'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/dashboard/blogs/'
    | '/dashboard/business-sectors/'
    | '/dashboard/gallery/'
    | '/dashboard/products/'
    | '/dashboard/services/'
    | '/dashboard/vacancies/'
    | '/dashboard/achievements/'
    | '/dashboard/client-projects/'
    | '/dashboard/contact-us/'
    | '/dashboard/faqs/'
    | '/dashboard/newsletter/'
    | '/dashboard/organizational-structure/'
    | '/dashboard/partners/'
    | '/dashboard/socials/'
    | '/dashboard/tags/'
    | '/dashboard/testimonials/'
    | '/dashboard/user-management/'
    | '/dashboard/achievements/$id/edit'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/achievements/$id/'
    | '/dashboard/blogs/$slug/'
    | '/dashboard/business-sectors/$slug/'
    | '/dashboard/client-projects/$slug/'
    | '/dashboard/contact-us/$id/'
    | '/dashboard/gallery/$id/'
    | '/dashboard/partners/$id/'
    | '/dashboard/products/$slug/'
    | '/dashboard/services/$slug/'
    | '/dashboard/testimonials/$id/'
    | '/dashboard/user-management/$userId/'
    | '/dashboard/vacancies/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForbiddenLazyRoute: typeof ForbiddenLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RateLimitLazyRoute: typeof RateLimitLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limit': {
      id: '/rate-limit'
      path: '/rate-limit'
      fullPath: '/rate-limit'
      preLoaderRoute: typeof RateLimitLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/terms-of-service': {
      id: '/_landing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LandingTermsOfServiceRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/services': {
      id: '/_landing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LandingServicesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy-policy': {
      id: '/_landing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LandingPrivacyPolicyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/gallery': {
      id: '/_landing/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof LandingGalleryRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/career': {
      id: '/_landing/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof LandingCareerRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/articles': {
      id: '/_landing/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof LandingArticlesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingRoute
    }
    '/dashboard/user-management/': {
      id: '/dashboard/user-management/'
      path: '/user-management'
      fullPath: '/dashboard/user-management'
      preLoaderRoute: typeof DashboardUserManagementIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/': {
      id: '/dashboard/testimonials/'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof DashboardTagsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/socials/': {
      id: '/dashboard/socials/'
      path: '/socials'
      fullPath: '/dashboard/socials'
      preLoaderRoute: typeof DashboardSocialsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/': {
      id: '/dashboard/partners/'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/organizational-structure/': {
      id: '/dashboard/organizational-structure/'
      path: '/organizational-structure'
      fullPath: '/dashboard/organizational-structure'
      preLoaderRoute: typeof DashboardOrganizationalStructureIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/newsletter/': {
      id: '/dashboard/newsletter/'
      path: '/newsletter'
      fullPath: '/dashboard/newsletter'
      preLoaderRoute: typeof DashboardNewsletterIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faqs/': {
      id: '/dashboard/faqs/'
      path: '/faqs'
      fullPath: '/dashboard/faqs'
      preLoaderRoute: typeof DashboardFaqsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/': {
      id: '/dashboard/contact-us/'
      path: '/contact-us'
      fullPath: '/dashboard/contact-us'
      preLoaderRoute: typeof DashboardContactUsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/': {
      id: '/dashboard/client-projects/'
      path: '/client-projects'
      fullPath: '/dashboard/client-projects'
      preLoaderRoute: typeof DashboardClientProjectsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements/': {
      id: '/dashboard/achievements/'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/': {
      id: '/dashboard/vacancies/'
      path: '/vacancies'
      fullPath: '/dashboard/vacancies'
      preLoaderRoute: typeof DashboardVacanciesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/': {
      id: '/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/': {
      id: '/dashboard/gallery/'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/': {
      id: '/dashboard/business-sectors/'
      path: '/business-sectors'
      fullPath: '/dashboard/business-sectors'
      preLoaderRoute: typeof DashboardBusinessSectorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/': {
      id: '/dashboard/blogs/'
      path: '/blogs'
      fullPath: '/dashboard/blogs'
      preLoaderRoute: typeof DashboardBlogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/create': {
      id: '/dashboard/vacancies/create'
      path: '/vacancies/create'
      fullPath: '/dashboard/vacancies/create'
      preLoaderRoute: typeof DashboardVacanciesCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/create': {
      id: '/dashboard/user-management/create'
      path: '/user-management/create'
      fullPath: '/dashboard/user-management/create'
      preLoaderRoute: typeof DashboardUserManagementCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/create': {
      id: '/dashboard/testimonials/create'
      path: '/testimonials/create'
      fullPath: '/dashboard/testimonials/create'
      preLoaderRoute: typeof DashboardTestimonialsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/create': {
      id: '/dashboard/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardProductsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/create': {
      id: '/dashboard/partners/create'
      path: '/partners/create'
      fullPath: '/dashboard/partners/create'
      preLoaderRoute: typeof DashboardPartnersCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/create': {
      id: '/dashboard/gallery/create'
      path: '/gallery/create'
      fullPath: '/dashboard/gallery/create'
      preLoaderRoute: typeof DashboardGalleryCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/create': {
      id: '/dashboard/contact-us/create'
      path: '/contact-us/create'
      fullPath: '/dashboard/contact-us/create'
      preLoaderRoute: typeof DashboardContactUsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/create': {
      id: '/dashboard/client-projects/create'
      path: '/client-projects/create'
      fullPath: '/dashboard/client-projects/create'
      preLoaderRoute: typeof DashboardClientProjectsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/create': {
      id: '/dashboard/blogs/create'
      path: '/blogs/create'
      fullPath: '/dashboard/blogs/create'
      preLoaderRoute: typeof DashboardBlogsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements/create': {
      id: '/dashboard/achievements/create'
      path: '/achievements/create'
      fullPath: '/dashboard/achievements/create'
      preLoaderRoute: typeof DashboardAchievementsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/create': {
      id: '/dashboard/services/create'
      path: '/services/create'
      fullPath: '/dashboard/services/create'
      preLoaderRoute: typeof DashboardServicesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/categories': {
      id: '/dashboard/gallery/categories'
      path: '/gallery/categories'
      fullPath: '/dashboard/gallery/categories'
      preLoaderRoute: typeof DashboardGalleryCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/create': {
      id: '/dashboard/business-sectors/create'
      path: '/business-sectors/create'
      fullPath: '/dashboard/business-sectors/create'
      preLoaderRoute: typeof DashboardBusinessSectorsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_landing/services/$slug': {
      id: '/_landing/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof LandingServicesSlugRouteImport
      parentRoute: typeof LandingServicesRoute
    }
    '/_landing/sectors/$slug': {
      id: '/_landing/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof LandingSectorsSlugRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/career/$slug': {
      id: '/_landing/career/$slug'
      path: '/$slug'
      fullPath: '/career/$slug'
      preLoaderRoute: typeof LandingCareerSlugRouteImport
      parentRoute: typeof LandingCareerRoute
    }
    '/_landing/articles/$slug': {
      id: '/_landing/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof LandingArticlesSlugRouteImport
      parentRoute: typeof LandingArticlesRoute
    }
    '/dashboard/vacancies/$slug/': {
      id: '/dashboard/vacancies/$slug/'
      path: '/vacancies/$slug'
      fullPath: '/dashboard/vacancies/$slug'
      preLoaderRoute: typeof DashboardVacanciesSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/$userId/': {
      id: '/dashboard/user-management/$userId/'
      path: '/user-management/$userId'
      fullPath: '/dashboard/user-management/$userId'
      preLoaderRoute: typeof DashboardUserManagementUserIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/$id/': {
      id: '/dashboard/testimonials/$id/'
      path: '/testimonials/$id'
      fullPath: '/dashboard/testimonials/$id'
      preLoaderRoute: typeof DashboardTestimonialsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$slug/': {
      id: '/dashboard/services/$slug/'
      path: '/services/$slug'
      fullPath: '/dashboard/services/$slug'
      preLoaderRoute: typeof DashboardServicesSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$slug/': {
      id: '/dashboard/products/$slug/'
      path: '/products/$slug'
      fullPath: '/dashboard/products/$slug'
      preLoaderRoute: typeof DashboardProductsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/$id/': {
      id: '/dashboard/partners/$id/'
      path: '/partners/$id'
      fullPath: '/dashboard/partners/$id'
      preLoaderRoute: typeof DashboardPartnersIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/$id/': {
      id: '/dashboard/gallery/$id/'
      path: '/gallery/$id'
      fullPath: '/dashboard/gallery/$id'
      preLoaderRoute: typeof DashboardGalleryIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/$id/': {
      id: '/dashboard/contact-us/$id/'
      path: '/contact-us/$id'
      fullPath: '/dashboard/contact-us/$id'
      preLoaderRoute: typeof DashboardContactUsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/$slug/': {
      id: '/dashboard/client-projects/$slug/'
      path: '/client-projects/$slug'
      fullPath: '/dashboard/client-projects/$slug'
      preLoaderRoute: typeof DashboardClientProjectsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/$slug/': {
      id: '/dashboard/business-sectors/$slug/'
      path: '/business-sectors/$slug'
      fullPath: '/dashboard/business-sectors/$slug'
      preLoaderRoute: typeof DashboardBusinessSectorsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/$slug/': {
      id: '/dashboard/blogs/$slug/'
      path: '/blogs/$slug'
      fullPath: '/dashboard/blogs/$slug'
      preLoaderRoute: typeof DashboardBlogsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements/$id/': {
      id: '/dashboard/achievements/$id/'
      path: '/achievements/$id'
      fullPath: '/dashboard/achievements/$id'
      preLoaderRoute: typeof DashboardAchievementsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/$slug/edit': {
      id: '/dashboard/vacancies/$slug/edit'
      path: '/vacancies/$slug/edit'
      fullPath: '/dashboard/vacancies/$slug/edit'
      preLoaderRoute: typeof DashboardVacanciesSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/$slug/applications': {
      id: '/dashboard/vacancies/$slug/applications'
      path: '/vacancies/$slug/applications'
      fullPath: '/dashboard/vacancies/$slug/applications'
      preLoaderRoute: typeof DashboardVacanciesSlugApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/$userId/edit': {
      id: '/dashboard/user-management/$userId/edit'
      path: '/user-management/$userId/edit'
      fullPath: '/dashboard/user-management/$userId/edit'
      preLoaderRoute: typeof DashboardUserManagementUserIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/$id/edit': {
      id: '/dashboard/testimonials/$id/edit'
      path: '/testimonials/$id/edit'
      fullPath: '/dashboard/testimonials/$id/edit'
      preLoaderRoute: typeof DashboardTestimonialsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$slug/edit': {
      id: '/dashboard/services/$slug/edit'
      path: '/services/$slug/edit'
      fullPath: '/dashboard/services/$slug/edit'
      preLoaderRoute: typeof DashboardServicesSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$slug/edit': {
      id: '/dashboard/products/$slug/edit'
      path: '/products/$slug/edit'
      fullPath: '/dashboard/products/$slug/edit'
      preLoaderRoute: typeof DashboardProductsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/$id/edit': {
      id: '/dashboard/partners/$id/edit'
      path: '/partners/$id/edit'
      fullPath: '/dashboard/partners/$id/edit'
      preLoaderRoute: typeof DashboardPartnersIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/$id/edit': {
      id: '/dashboard/gallery/$id/edit'
      path: '/gallery/$id/edit'
      fullPath: '/dashboard/gallery/$id/edit'
      preLoaderRoute: typeof DashboardGalleryIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/$id/edit': {
      id: '/dashboard/contact-us/$id/edit'
      path: '/contact-us/$id/edit'
      fullPath: '/dashboard/contact-us/$id/edit'
      preLoaderRoute: typeof DashboardContactUsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/$slug/edit': {
      id: '/dashboard/client-projects/$slug/edit'
      path: '/client-projects/$slug/edit'
      fullPath: '/dashboard/client-projects/$slug/edit'
      preLoaderRoute: typeof DashboardClientProjectsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/$slug/edit': {
      id: '/dashboard/business-sectors/$slug/edit'
      path: '/business-sectors/$slug/edit'
      fullPath: '/dashboard/business-sectors/$slug/edit'
      preLoaderRoute: typeof DashboardBusinessSectorsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/$slug/edit': {
      id: '/dashboard/blogs/$slug/edit'
      path: '/blogs/$slug/edit'
      fullPath: '/dashboard/blogs/$slug/edit'
      preLoaderRoute: typeof DashboardBlogsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements/$id/edit': {
      id: '/dashboard/achievements/$id/edit'
      path: '/achievements/$id/edit'
      fullPath: '/dashboard/achievements/$id/edit'
      preLoaderRoute: typeof DashboardAchievementsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface LandingArticlesRouteChildren {
  LandingArticlesSlugRoute: typeof LandingArticlesSlugRoute
}

const LandingArticlesRouteChildren: LandingArticlesRouteChildren = {
  LandingArticlesSlugRoute: LandingArticlesSlugRoute,
}

const LandingArticlesRouteWithChildren = LandingArticlesRoute._addFileChildren(
  LandingArticlesRouteChildren,
)

interface LandingCareerRouteChildren {
  LandingCareerSlugRoute: typeof LandingCareerSlugRoute
}

const LandingCareerRouteChildren: LandingCareerRouteChildren = {
  LandingCareerSlugRoute: LandingCareerSlugRoute,
}

const LandingCareerRouteWithChildren = LandingCareerRoute._addFileChildren(
  LandingCareerRouteChildren,
)

interface LandingServicesRouteChildren {
  LandingServicesSlugRoute: typeof LandingServicesSlugRoute
}

const LandingServicesRouteChildren: LandingServicesRouteChildren = {
  LandingServicesSlugRoute: LandingServicesSlugRoute,
}

const LandingServicesRouteWithChildren = LandingServicesRoute._addFileChildren(
  LandingServicesRouteChildren,
)

interface LandingRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingArticlesRoute: typeof LandingArticlesRouteWithChildren
  LandingCareerRoute: typeof LandingCareerRouteWithChildren
  LandingContactRoute: typeof LandingContactRoute
  LandingGalleryRoute: typeof LandingGalleryRoute
  LandingPrivacyPolicyRoute: typeof LandingPrivacyPolicyRoute
  LandingServicesRoute: typeof LandingServicesRouteWithChildren
  LandingTermsOfServiceRoute: typeof LandingTermsOfServiceRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingSectorsSlugRoute: typeof LandingSectorsSlugRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingArticlesRoute: LandingArticlesRouteWithChildren,
  LandingCareerRoute: LandingCareerRouteWithChildren,
  LandingContactRoute: LandingContactRoute,
  LandingGalleryRoute: LandingGalleryRoute,
  LandingPrivacyPolicyRoute: LandingPrivacyPolicyRoute,
  LandingServicesRoute: LandingServicesRouteWithChildren,
  LandingTermsOfServiceRoute: LandingTermsOfServiceRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingSectorsSlugRoute: LandingSectorsSlugRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBusinessSectorsCreateRoute: typeof DashboardBusinessSectorsCreateRoute
  DashboardGalleryCategoriesRoute: typeof DashboardGalleryCategoriesRoute
  DashboardServicesCreateRoute: typeof DashboardServicesCreateRoute
  DashboardAchievementsCreateLazyRoute: typeof DashboardAchievementsCreateLazyRoute
  DashboardBlogsCreateLazyRoute: typeof DashboardBlogsCreateLazyRoute
  DashboardClientProjectsCreateLazyRoute: typeof DashboardClientProjectsCreateLazyRoute
  DashboardContactUsCreateLazyRoute: typeof DashboardContactUsCreateLazyRoute
  DashboardGalleryCreateLazyRoute: typeof DashboardGalleryCreateLazyRoute
  DashboardPartnersCreateLazyRoute: typeof DashboardPartnersCreateLazyRoute
  DashboardProductsCreateLazyRoute: typeof DashboardProductsCreateLazyRoute
  DashboardTestimonialsCreateLazyRoute: typeof DashboardTestimonialsCreateLazyRoute
  DashboardUserManagementCreateLazyRoute: typeof DashboardUserManagementCreateLazyRoute
  DashboardVacanciesCreateLazyRoute: typeof DashboardVacanciesCreateLazyRoute
  DashboardBlogsIndexRoute: typeof DashboardBlogsIndexRoute
  DashboardBusinessSectorsIndexRoute: typeof DashboardBusinessSectorsIndexRoute
  DashboardGalleryIndexRoute: typeof DashboardGalleryIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardServicesIndexRoute: typeof DashboardServicesIndexRoute
  DashboardVacanciesIndexRoute: typeof DashboardVacanciesIndexRoute
  DashboardAchievementsIndexLazyRoute: typeof DashboardAchievementsIndexLazyRoute
  DashboardClientProjectsIndexLazyRoute: typeof DashboardClientProjectsIndexLazyRoute
  DashboardContactUsIndexLazyRoute: typeof DashboardContactUsIndexLazyRoute
  DashboardFaqsIndexLazyRoute: typeof DashboardFaqsIndexLazyRoute
  DashboardNewsletterIndexLazyRoute: typeof DashboardNewsletterIndexLazyRoute
  DashboardOrganizationalStructureIndexLazyRoute: typeof DashboardOrganizationalStructureIndexLazyRoute
  DashboardPartnersIndexLazyRoute: typeof DashboardPartnersIndexLazyRoute
  DashboardSocialsIndexLazyRoute: typeof DashboardSocialsIndexLazyRoute
  DashboardTagsIndexLazyRoute: typeof DashboardTagsIndexLazyRoute
  DashboardTestimonialsIndexLazyRoute: typeof DashboardTestimonialsIndexLazyRoute
  DashboardUserManagementIndexLazyRoute: typeof DashboardUserManagementIndexLazyRoute
  DashboardAchievementsIdEditRoute: typeof DashboardAchievementsIdEditRoute
  DashboardBlogsSlugEditRoute: typeof DashboardBlogsSlugEditRoute
  DashboardBusinessSectorsSlugEditRoute: typeof DashboardBusinessSectorsSlugEditRoute
  DashboardClientProjectsSlugEditRoute: typeof DashboardClientProjectsSlugEditRoute
  DashboardContactUsIdEditRoute: typeof DashboardContactUsIdEditRoute
  DashboardGalleryIdEditRoute: typeof DashboardGalleryIdEditRoute
  DashboardPartnersIdEditRoute: typeof DashboardPartnersIdEditRoute
  DashboardProductsSlugEditRoute: typeof DashboardProductsSlugEditRoute
  DashboardServicesSlugEditRoute: typeof DashboardServicesSlugEditRoute
  DashboardTestimonialsIdEditRoute: typeof DashboardTestimonialsIdEditRoute
  DashboardUserManagementUserIdEditRoute: typeof DashboardUserManagementUserIdEditRoute
  DashboardVacanciesSlugApplicationsRoute: typeof DashboardVacanciesSlugApplicationsRoute
  DashboardVacanciesSlugEditRoute: typeof DashboardVacanciesSlugEditRoute
  DashboardAchievementsIdIndexRoute: typeof DashboardAchievementsIdIndexRoute
  DashboardBlogsSlugIndexRoute: typeof DashboardBlogsSlugIndexRoute
  DashboardBusinessSectorsSlugIndexRoute: typeof DashboardBusinessSectorsSlugIndexRoute
  DashboardClientProjectsSlugIndexRoute: typeof DashboardClientProjectsSlugIndexRoute
  DashboardContactUsIdIndexRoute: typeof DashboardContactUsIdIndexRoute
  DashboardGalleryIdIndexRoute: typeof DashboardGalleryIdIndexRoute
  DashboardPartnersIdIndexRoute: typeof DashboardPartnersIdIndexRoute
  DashboardProductsSlugIndexRoute: typeof DashboardProductsSlugIndexRoute
  DashboardServicesSlugIndexRoute: typeof DashboardServicesSlugIndexRoute
  DashboardTestimonialsIdIndexRoute: typeof DashboardTestimonialsIdIndexRoute
  DashboardUserManagementUserIdIndexRoute: typeof DashboardUserManagementUserIdIndexRoute
  DashboardVacanciesSlugIndexRoute: typeof DashboardVacanciesSlugIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBusinessSectorsCreateRoute: DashboardBusinessSectorsCreateRoute,
  DashboardGalleryCategoriesRoute: DashboardGalleryCategoriesRoute,
  DashboardServicesCreateRoute: DashboardServicesCreateRoute,
  DashboardAchievementsCreateLazyRoute: DashboardAchievementsCreateLazyRoute,
  DashboardBlogsCreateLazyRoute: DashboardBlogsCreateLazyRoute,
  DashboardClientProjectsCreateLazyRoute:
    DashboardClientProjectsCreateLazyRoute,
  DashboardContactUsCreateLazyRoute: DashboardContactUsCreateLazyRoute,
  DashboardGalleryCreateLazyRoute: DashboardGalleryCreateLazyRoute,
  DashboardPartnersCreateLazyRoute: DashboardPartnersCreateLazyRoute,
  DashboardProductsCreateLazyRoute: DashboardProductsCreateLazyRoute,
  DashboardTestimonialsCreateLazyRoute: DashboardTestimonialsCreateLazyRoute,
  DashboardUserManagementCreateLazyRoute:
    DashboardUserManagementCreateLazyRoute,
  DashboardVacanciesCreateLazyRoute: DashboardVacanciesCreateLazyRoute,
  DashboardBlogsIndexRoute: DashboardBlogsIndexRoute,
  DashboardBusinessSectorsIndexRoute: DashboardBusinessSectorsIndexRoute,
  DashboardGalleryIndexRoute: DashboardGalleryIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardServicesIndexRoute: DashboardServicesIndexRoute,
  DashboardVacanciesIndexRoute: DashboardVacanciesIndexRoute,
  DashboardAchievementsIndexLazyRoute: DashboardAchievementsIndexLazyRoute,
  DashboardClientProjectsIndexLazyRoute: DashboardClientProjectsIndexLazyRoute,
  DashboardContactUsIndexLazyRoute: DashboardContactUsIndexLazyRoute,
  DashboardFaqsIndexLazyRoute: DashboardFaqsIndexLazyRoute,
  DashboardNewsletterIndexLazyRoute: DashboardNewsletterIndexLazyRoute,
  DashboardOrganizationalStructureIndexLazyRoute:
    DashboardOrganizationalStructureIndexLazyRoute,
  DashboardPartnersIndexLazyRoute: DashboardPartnersIndexLazyRoute,
  DashboardSocialsIndexLazyRoute: DashboardSocialsIndexLazyRoute,
  DashboardTagsIndexLazyRoute: DashboardTagsIndexLazyRoute,
  DashboardTestimonialsIndexLazyRoute: DashboardTestimonialsIndexLazyRoute,
  DashboardUserManagementIndexLazyRoute: DashboardUserManagementIndexLazyRoute,
  DashboardAchievementsIdEditRoute: DashboardAchievementsIdEditRoute,
  DashboardBlogsSlugEditRoute: DashboardBlogsSlugEditRoute,
  DashboardBusinessSectorsSlugEditRoute: DashboardBusinessSectorsSlugEditRoute,
  DashboardClientProjectsSlugEditRoute: DashboardClientProjectsSlugEditRoute,
  DashboardContactUsIdEditRoute: DashboardContactUsIdEditRoute,
  DashboardGalleryIdEditRoute: DashboardGalleryIdEditRoute,
  DashboardPartnersIdEditRoute: DashboardPartnersIdEditRoute,
  DashboardProductsSlugEditRoute: DashboardProductsSlugEditRoute,
  DashboardServicesSlugEditRoute: DashboardServicesSlugEditRoute,
  DashboardTestimonialsIdEditRoute: DashboardTestimonialsIdEditRoute,
  DashboardUserManagementUserIdEditRoute:
    DashboardUserManagementUserIdEditRoute,
  DashboardVacanciesSlugApplicationsRoute:
    DashboardVacanciesSlugApplicationsRoute,
  DashboardVacanciesSlugEditRoute: DashboardVacanciesSlugEditRoute,
  DashboardAchievementsIdIndexRoute: DashboardAchievementsIdIndexRoute,
  DashboardBlogsSlugIndexRoute: DashboardBlogsSlugIndexRoute,
  DashboardBusinessSectorsSlugIndexRoute:
    DashboardBusinessSectorsSlugIndexRoute,
  DashboardClientProjectsSlugIndexRoute: DashboardClientProjectsSlugIndexRoute,
  DashboardContactUsIdIndexRoute: DashboardContactUsIdIndexRoute,
  DashboardGalleryIdIndexRoute: DashboardGalleryIdIndexRoute,
  DashboardPartnersIdIndexRoute: DashboardPartnersIdIndexRoute,
  DashboardProductsSlugIndexRoute: DashboardProductsSlugIndexRoute,
  DashboardServicesSlugIndexRoute: DashboardServicesSlugIndexRoute,
  DashboardTestimonialsIdIndexRoute: DashboardTestimonialsIdIndexRoute,
  DashboardUserManagementUserIdIndexRoute:
    DashboardUserManagementUserIdIndexRoute,
  DashboardVacanciesSlugIndexRoute: DashboardVacanciesSlugIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForbiddenLazyRoute: ForbiddenLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  RateLimitLazyRoute: RateLimitLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
