/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteScheduleRouteImport } from './routes/_site/schedule'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as DashboardVacanciesIndexRouteImport } from './routes/dashboard/vacancies/index'
import { Route as DashboardServicesIndexRouteImport } from './routes/dashboard/services/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardGalleryIndexRouteImport } from './routes/dashboard/gallery/index'
import { Route as DashboardBusinessSectorsIndexRouteImport } from './routes/dashboard/business-sectors/index'
import { Route as DashboardBlogsIndexRouteImport } from './routes/dashboard/blogs/index'
import { Route as SiteServicesIndexRouteImport } from './routes/_site/services.index'
import { Route as SiteSectorsIndexRouteImport } from './routes/_site/sectors.index'
import { Route as SiteProjectsIndexRouteImport } from './routes/_site/projects.index'
import { Route as SiteGalleryIndexRouteImport } from './routes/_site/gallery.index'
import { Route as SiteCareersIndexRouteImport } from './routes/_site/careers.index'
import { Route as SiteBlogsIndexRouteImport } from './routes/_site/blogs.index'
import { Route as DashboardServicesCreateRouteImport } from './routes/dashboard/services/create'
import { Route as DashboardGalleryCategoriesRouteImport } from './routes/dashboard/gallery/categories'
import { Route as DashboardBusinessSectorsCreateRouteImport } from './routes/dashboard/business-sectors/create'
import { Route as SiteServicesSlugRouteImport } from './routes/_site/services.$slug'
import { Route as SiteSectorsSlugRouteImport } from './routes/_site/sectors.$slug'
import { Route as SiteProjectsSlugRouteImport } from './routes/_site/projects.$slug'
import { Route as SiteCareersSlugRouteImport } from './routes/_site/careers.$slug'
import { Route as SiteBlogsSlugRouteImport } from './routes/_site/blogs.$slug'
import { Route as DashboardVacanciesSlugIndexRouteImport } from './routes/dashboard/vacancies/$slug/index'
import { Route as DashboardUserManagementUserIdIndexRouteImport } from './routes/dashboard/user-management/$userId/index'
import { Route as DashboardTestimonialsIdIndexRouteImport } from './routes/dashboard/testimonials/$id/index'
import { Route as DashboardServicesSlugIndexRouteImport } from './routes/dashboard/services/$slug/index'
import { Route as DashboardProductsSlugIndexRouteImport } from './routes/dashboard/products/$slug/index'
import { Route as DashboardPartnersIdIndexRouteImport } from './routes/dashboard/partners/$id/index'
import { Route as DashboardGalleryIdIndexRouteImport } from './routes/dashboard/gallery/$id/index'
import { Route as DashboardContactUsIdIndexRouteImport } from './routes/dashboard/contact-us/$id/index'
import { Route as DashboardClientProjectsSlugIndexRouteImport } from './routes/dashboard/client-projects/$slug/index'
import { Route as DashboardBusinessSectorsSlugIndexRouteImport } from './routes/dashboard/business-sectors/$slug/index'
import { Route as DashboardBlogsSlugIndexRouteImport } from './routes/dashboard/blogs/$slug/index'
import { Route as DashboardVacanciesSlugEditRouteImport } from './routes/dashboard/vacancies/$slug/edit'
import { Route as DashboardVacanciesSlugApplicationsRouteImport } from './routes/dashboard/vacancies/$slug/applications'
import { Route as DashboardUserManagementUserIdEditRouteImport } from './routes/dashboard/user-management/$userId/edit'
import { Route as DashboardTestimonialsIdEditRouteImport } from './routes/dashboard/testimonials/$id/edit'
import { Route as DashboardServicesSlugEditRouteImport } from './routes/dashboard/services/$slug/edit'
import { Route as DashboardProductsSlugEditRouteImport } from './routes/dashboard/products/$slug/edit'
import { Route as DashboardPartnersIdEditRouteImport } from './routes/dashboard/partners/$id/edit'
import { Route as DashboardGalleryIdEditRouteImport } from './routes/dashboard/gallery/$id/edit'
import { Route as DashboardContactUsIdEditRouteImport } from './routes/dashboard/contact-us/$id/edit'
import { Route as DashboardClientProjectsSlugEditRouteImport } from './routes/dashboard/client-projects/$slug/edit'
import { Route as DashboardBusinessSectorsSlugEditRouteImport } from './routes/dashboard/business-sectors/$slug/edit'
import { Route as DashboardBlogsSlugEditRouteImport } from './routes/dashboard/blogs/$slug/edit'

const RegisterLazyRouteImport = createFileRoute('/register')()
const RateLimitLazyRouteImport = createFileRoute('/rate-limit')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ForbiddenLazyRouteImport = createFileRoute('/forbidden')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardUserManagementIndexLazyRouteImport = createFileRoute(
  '/dashboard/user-management/',
)()
const DashboardTestimonialsIndexLazyRouteImport = createFileRoute(
  '/dashboard/testimonials/',
)()
const DashboardTagsIndexLazyRouteImport = createFileRoute('/dashboard/tags/')()
const DashboardSocialsIndexLazyRouteImport = createFileRoute(
  '/dashboard/socials/',
)()
const DashboardPartnersIndexLazyRouteImport = createFileRoute(
  '/dashboard/partners/',
)()
const DashboardOrganizationalStructureIndexLazyRouteImport = createFileRoute(
  '/dashboard/organizational-structure/',
)()
const DashboardFaqsIndexLazyRouteImport = createFileRoute('/dashboard/faqs/')()
const DashboardContactUsIndexLazyRouteImport = createFileRoute(
  '/dashboard/contact-us/',
)()
const DashboardClientProjectsIndexLazyRouteImport = createFileRoute(
  '/dashboard/client-projects/',
)()
const DashboardVacanciesCreateLazyRouteImport = createFileRoute(
  '/dashboard/vacancies/create',
)()
const DashboardUserManagementCreateLazyRouteImport = createFileRoute(
  '/dashboard/user-management/create',
)()
const DashboardTestimonialsCreateLazyRouteImport = createFileRoute(
  '/dashboard/testimonials/create',
)()
const DashboardProductsCreateLazyRouteImport = createFileRoute(
  '/dashboard/products/create',
)()
const DashboardPartnersCreateLazyRouteImport = createFileRoute(
  '/dashboard/partners/create',
)()
const DashboardGalleryCreateLazyRouteImport = createFileRoute(
  '/dashboard/gallery/create',
)()
const DashboardContactUsCreateLazyRouteImport = createFileRoute(
  '/dashboard/contact-us/create',
)()
const DashboardClientProjectsCreateLazyRouteImport = createFileRoute(
  '/dashboard/client-projects/create',
)()
const DashboardBlogsCreateLazyRouteImport = createFileRoute(
  '/dashboard/blogs/create',
)()

const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const RateLimitLazyRoute = RateLimitLazyRouteImport.update({
  id: '/rate-limit',
  path: '/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/rate-limit.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForbiddenLazyRoute = ForbiddenLazyRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/forbidden.lazy').then((d) => d.Route))
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any).lazy(() => import('./routes/_site/index.lazy').then((d) => d.Route))
const SiteScheduleRoute = SiteScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/schedule.lazy').then((d) => d.Route),
)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any).lazy(() => import('./routes/_site/contact.lazy').then((d) => d.Route))
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any).lazy(() => import('./routes/_site/about.lazy').then((d) => d.Route))
const DashboardUserManagementIndexLazyRoute =
  DashboardUserManagementIndexLazyRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIndexLazyRoute =
  DashboardTestimonialsIndexLazyRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/index.lazy').then((d) => d.Route),
  )
const DashboardTagsIndexLazyRoute = DashboardTagsIndexLazyRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/tags/index.lazy').then((d) => d.Route),
)
const DashboardSocialsIndexLazyRoute =
  DashboardSocialsIndexLazyRouteImport.update({
    id: '/socials/',
    path: '/socials/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/socials/index.lazy').then((d) => d.Route),
  )
const DashboardPartnersIndexLazyRoute =
  DashboardPartnersIndexLazyRouteImport.update({
    id: '/partners/',
    path: '/partners/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/index.lazy').then((d) => d.Route),
  )
const DashboardOrganizationalStructureIndexLazyRoute =
  DashboardOrganizationalStructureIndexLazyRouteImport.update({
    id: '/organizational-structure/',
    path: '/organizational-structure/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/organizational-structure/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardFaqsIndexLazyRoute = DashboardFaqsIndexLazyRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/faqs/index.lazy').then((d) => d.Route),
)
const DashboardContactUsIndexLazyRoute =
  DashboardContactUsIndexLazyRouteImport.update({
    id: '/contact-us/',
    path: '/contact-us/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/index.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsIndexLazyRoute =
  DashboardClientProjectsIndexLazyRouteImport.update({
    id: '/client-projects/',
    path: '/client-projects/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardVacanciesIndexRoute = DashboardVacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/vacancies/index.lazy').then((d) => d.Route),
)
const DashboardServicesIndexRoute = DashboardServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/services/index.lazy').then((d) => d.Route),
)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/products/index.lazy').then((d) => d.Route),
)
const DashboardGalleryIndexRoute = DashboardGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/index.lazy').then((d) => d.Route),
)
const DashboardBusinessSectorsIndexRoute =
  DashboardBusinessSectorsIndexRouteImport.update({
    id: '/business-sectors/',
    path: '/business-sectors/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsIndexRoute = DashboardBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/index.lazy').then((d) => d.Route),
)
const SiteServicesIndexRoute = SiteServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/services.index.lazy').then((d) => d.Route),
)
const SiteSectorsIndexRoute = SiteSectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/sectors.index.lazy').then((d) => d.Route),
)
const SiteProjectsIndexRoute = SiteProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/projects.index.lazy').then((d) => d.Route),
)
const SiteGalleryIndexRoute = SiteGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/gallery.index.lazy').then((d) => d.Route),
)
const SiteCareersIndexRoute = SiteCareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/careers.index.lazy').then((d) => d.Route),
)
const SiteBlogsIndexRoute = SiteBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/blogs.index.lazy').then((d) => d.Route),
)
const DashboardVacanciesCreateLazyRoute =
  DashboardVacanciesCreateLazyRouteImport.update({
    id: '/vacancies/create',
    path: '/vacancies/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/create.lazy').then((d) => d.Route),
  )
const DashboardUserManagementCreateLazyRoute =
  DashboardUserManagementCreateLazyRouteImport.update({
    id: '/user-management/create',
    path: '/user-management/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsCreateLazyRoute =
  DashboardTestimonialsCreateLazyRouteImport.update({
    id: '/testimonials/create',
    path: '/testimonials/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/create.lazy').then((d) => d.Route),
  )
const DashboardProductsCreateLazyRoute =
  DashboardProductsCreateLazyRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/create.lazy').then((d) => d.Route),
  )
const DashboardPartnersCreateLazyRoute =
  DashboardPartnersCreateLazyRouteImport.update({
    id: '/partners/create',
    path: '/partners/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/create.lazy').then((d) => d.Route),
  )
const DashboardGalleryCreateLazyRoute =
  DashboardGalleryCreateLazyRouteImport.update({
    id: '/gallery/create',
    path: '/gallery/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/gallery/create.lazy').then((d) => d.Route),
  )
const DashboardContactUsCreateLazyRoute =
  DashboardContactUsCreateLazyRouteImport.update({
    id: '/contact-us/create',
    path: '/contact-us/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/create.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsCreateLazyRoute =
  DashboardClientProjectsCreateLazyRouteImport.update({
    id: '/client-projects/create',
    path: '/client-projects/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsCreateLazyRoute =
  DashboardBlogsCreateLazyRouteImport.update({
    id: '/blogs/create',
    path: '/blogs/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/blogs/create.lazy').then((d) => d.Route),
  )
const DashboardServicesCreateRoute = DashboardServicesCreateRouteImport.update({
  id: '/services/create',
  path: '/services/create',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/services/create.lazy').then((d) => d.Route),
)
const DashboardGalleryCategoriesRoute =
  DashboardGalleryCategoriesRouteImport.update({
    id: '/gallery/categories',
    path: '/gallery/categories',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/gallery/categories.lazy').then((d) => d.Route),
  )
const DashboardBusinessSectorsCreateRoute =
  DashboardBusinessSectorsCreateRouteImport.update({
    id: '/business-sectors/create',
    path: '/business-sectors/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/create.lazy').then(
      (d) => d.Route,
    ),
  )
const SiteServicesSlugRoute = SiteServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/services.$slug.lazy').then((d) => d.Route),
)
const SiteSectorsSlugRoute = SiteSectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/sectors.$slug.lazy').then((d) => d.Route),
)
const SiteProjectsSlugRoute = SiteProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/projects.$slug.lazy').then((d) => d.Route),
)
const SiteCareersSlugRoute = SiteCareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/careers.$slug.lazy').then((d) => d.Route),
)
const SiteBlogsSlugRoute = SiteBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/blogs.$slug.lazy').then((d) => d.Route),
)
const DashboardVacanciesSlugIndexRoute =
  DashboardVacanciesSlugIndexRouteImport.update({
    id: '/vacancies/$slug/',
    path: '/vacancies/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardUserManagementUserIdIndexRoute =
  DashboardUserManagementUserIdIndexRouteImport.update({
    id: '/user-management/$userId/',
    path: '/user-management/$userId/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/$userId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIdIndexRoute =
  DashboardTestimonialsIdIndexRouteImport.update({
    id: '/testimonials/$id/',
    path: '/testimonials/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardServicesSlugIndexRoute =
  DashboardServicesSlugIndexRouteImport.update({
    id: '/services/$slug/',
    path: '/services/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/services/$slug/index.lazy').then((d) => d.Route),
  )
const DashboardProductsSlugIndexRoute =
  DashboardProductsSlugIndexRouteImport.update({
    id: '/products/$slug/',
    path: '/products/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/$slug/index.lazy').then((d) => d.Route),
  )
const DashboardPartnersIdIndexRoute =
  DashboardPartnersIdIndexRouteImport.update({
    id: '/partners/$id/',
    path: '/partners/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/$id/index.lazy').then((d) => d.Route),
  )
const DashboardGalleryIdIndexRoute = DashboardGalleryIdIndexRouteImport.update({
  id: '/gallery/$id/',
  path: '/gallery/$id/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/$id/index.lazy').then((d) => d.Route),
)
const DashboardContactUsIdIndexRoute =
  DashboardContactUsIdIndexRouteImport.update({
    id: '/contact-us/$id/',
    path: '/contact-us/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/$id/index.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsSlugIndexRoute =
  DashboardClientProjectsSlugIndexRouteImport.update({
    id: '/client-projects/$slug/',
    path: '/client-projects/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBusinessSectorsSlugIndexRoute =
  DashboardBusinessSectorsSlugIndexRouteImport.update({
    id: '/business-sectors/$slug/',
    path: '/business-sectors/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsSlugIndexRoute = DashboardBlogsSlugIndexRouteImport.update({
  id: '/blogs/$slug/',
  path: '/blogs/$slug/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/$slug/index.lazy').then((d) => d.Route),
)
const DashboardVacanciesSlugEditRoute =
  DashboardVacanciesSlugEditRouteImport.update({
    id: '/vacancies/$slug/edit',
    path: '/vacancies/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardVacanciesSlugApplicationsRoute =
  DashboardVacanciesSlugApplicationsRouteImport.update({
    id: '/vacancies/$slug/applications',
    path: '/vacancies/$slug/applications',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/applications.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardUserManagementUserIdEditRoute =
  DashboardUserManagementUserIdEditRouteImport.update({
    id: '/user-management/$userId/edit',
    path: '/user-management/$userId/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/$userId/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIdEditRoute =
  DashboardTestimonialsIdEditRouteImport.update({
    id: '/testimonials/$id/edit',
    path: '/testimonials/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardServicesSlugEditRoute =
  DashboardServicesSlugEditRouteImport.update({
    id: '/services/$slug/edit',
    path: '/services/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/services/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardProductsSlugEditRoute =
  DashboardProductsSlugEditRouteImport.update({
    id: '/products/$slug/edit',
    path: '/products/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardPartnersIdEditRoute = DashboardPartnersIdEditRouteImport.update({
  id: '/partners/$id/edit',
  path: '/partners/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/partners/$id/edit.lazy').then((d) => d.Route),
)
const DashboardGalleryIdEditRoute = DashboardGalleryIdEditRouteImport.update({
  id: '/gallery/$id/edit',
  path: '/gallery/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/$id/edit.lazy').then((d) => d.Route),
)
const DashboardContactUsIdEditRoute =
  DashboardContactUsIdEditRouteImport.update({
    id: '/contact-us/$id/edit',
    path: '/contact-us/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/$id/edit.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsSlugEditRoute =
  DashboardClientProjectsSlugEditRouteImport.update({
    id: '/client-projects/$slug/edit',
    path: '/client-projects/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/$slug/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBusinessSectorsSlugEditRoute =
  DashboardBusinessSectorsSlugEditRouteImport.update({
    id: '/business-sectors/$slug/edit',
    path: '/business-sectors/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/$slug/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsSlugEditRoute = DashboardBlogsSlugEditRouteImport.update({
  id: '/blogs/$slug/edit',
  path: '/blogs/$slug/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/$slug/edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/schedule': typeof SiteScheduleRoute
  '/': typeof SiteIndexRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/blogs/$slug': typeof SiteBlogsSlugRoute
  '/careers/$slug': typeof SiteCareersSlugRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/sectors/$slug': typeof SiteSectorsSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/blogs': typeof SiteBlogsIndexRoute
  '/careers': typeof SiteCareersIndexRoute
  '/gallery': typeof SiteGalleryIndexRoute
  '/projects': typeof SiteProjectsIndexRoute
  '/sectors': typeof SiteSectorsIndexRoute
  '/services': typeof SiteServicesIndexRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery': typeof DashboardGalleryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies': typeof DashboardVacanciesIndexRoute
  '/dashboard/client-projects': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/organizational-structure': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/schedule': typeof SiteScheduleRoute
  '/': typeof SiteIndexRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/blogs/$slug': typeof SiteBlogsSlugRoute
  '/careers/$slug': typeof SiteCareersSlugRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
  '/sectors/$slug': typeof SiteSectorsSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/blogs': typeof SiteBlogsIndexRoute
  '/careers': typeof SiteCareersIndexRoute
  '/gallery': typeof SiteGalleryIndexRoute
  '/projects': typeof SiteProjectsIndexRoute
  '/sectors': typeof SiteSectorsIndexRoute
  '/services': typeof SiteServicesIndexRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery': typeof DashboardGalleryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies': typeof DashboardVacanciesIndexRoute
  '/dashboard/client-projects': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/organizational-structure': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/schedule': typeof SiteScheduleRoute
  '/_site/': typeof SiteIndexRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/_site/blogs/$slug': typeof SiteBlogsSlugRoute
  '/_site/careers/$slug': typeof SiteCareersSlugRoute
  '/_site/projects/$slug': typeof SiteProjectsSlugRoute
  '/_site/sectors/$slug': typeof SiteSectorsSlugRoute
  '/_site/services/$slug': typeof SiteServicesSlugRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/_site/blogs/': typeof SiteBlogsIndexRoute
  '/_site/careers/': typeof SiteCareersIndexRoute
  '/_site/gallery/': typeof SiteGalleryIndexRoute
  '/_site/projects/': typeof SiteProjectsIndexRoute
  '/_site/sectors/': typeof SiteSectorsIndexRoute
  '/_site/services/': typeof SiteServicesIndexRoute
  '/dashboard/blogs/': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors/': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery/': typeof DashboardGalleryIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies/': typeof DashboardVacanciesIndexRoute
  '/dashboard/client-projects/': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us/': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs/': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/organizational-structure/': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners/': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials/': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags/': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials/': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management/': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/blogs/$slug/': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug/': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug/': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id/': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id/': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id/': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug/': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug/': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id/': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId/': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug/': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/about'
    | '/contact'
    | '/schedule'
    | '/'
    | '/dashboard/'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/projects/$slug'
    | '/sectors/$slug'
    | '/services/$slug'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/blogs'
    | '/careers'
    | '/gallery'
    | '/projects'
    | '/sectors'
    | '/services'
    | '/dashboard/blogs'
    | '/dashboard/business-sectors'
    | '/dashboard/gallery'
    | '/dashboard/products'
    | '/dashboard/services'
    | '/dashboard/vacancies'
    | '/dashboard/client-projects'
    | '/dashboard/contact-us'
    | '/dashboard/faqs'
    | '/dashboard/organizational-structure'
    | '/dashboard/partners'
    | '/dashboard/socials'
    | '/dashboard/tags'
    | '/dashboard/testimonials'
    | '/dashboard/user-management'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/blogs/$slug'
    | '/dashboard/business-sectors/$slug'
    | '/dashboard/client-projects/$slug'
    | '/dashboard/contact-us/$id'
    | '/dashboard/gallery/$id'
    | '/dashboard/partners/$id'
    | '/dashboard/products/$slug'
    | '/dashboard/services/$slug'
    | '/dashboard/testimonials/$id'
    | '/dashboard/user-management/$userId'
    | '/dashboard/vacancies/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/about'
    | '/contact'
    | '/schedule'
    | '/'
    | '/dashboard'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/projects/$slug'
    | '/sectors/$slug'
    | '/services/$slug'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/blogs'
    | '/careers'
    | '/gallery'
    | '/projects'
    | '/sectors'
    | '/services'
    | '/dashboard/blogs'
    | '/dashboard/business-sectors'
    | '/dashboard/gallery'
    | '/dashboard/products'
    | '/dashboard/services'
    | '/dashboard/vacancies'
    | '/dashboard/client-projects'
    | '/dashboard/contact-us'
    | '/dashboard/faqs'
    | '/dashboard/organizational-structure'
    | '/dashboard/partners'
    | '/dashboard/socials'
    | '/dashboard/tags'
    | '/dashboard/testimonials'
    | '/dashboard/user-management'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/blogs/$slug'
    | '/dashboard/business-sectors/$slug'
    | '/dashboard/client-projects/$slug'
    | '/dashboard/contact-us/$id'
    | '/dashboard/gallery/$id'
    | '/dashboard/partners/$id'
    | '/dashboard/products/$slug'
    | '/dashboard/services/$slug'
    | '/dashboard/testimonials/$id'
    | '/dashboard/user-management/$userId'
    | '/dashboard/vacancies/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/schedule'
    | '/_site/'
    | '/dashboard/'
    | '/_site/blogs/$slug'
    | '/_site/careers/$slug'
    | '/_site/projects/$slug'
    | '/_site/sectors/$slug'
    | '/_site/services/$slug'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/_site/blogs/'
    | '/_site/careers/'
    | '/_site/gallery/'
    | '/_site/projects/'
    | '/_site/sectors/'
    | '/_site/services/'
    | '/dashboard/blogs/'
    | '/dashboard/business-sectors/'
    | '/dashboard/gallery/'
    | '/dashboard/products/'
    | '/dashboard/services/'
    | '/dashboard/vacancies/'
    | '/dashboard/client-projects/'
    | '/dashboard/contact-us/'
    | '/dashboard/faqs/'
    | '/dashboard/organizational-structure/'
    | '/dashboard/partners/'
    | '/dashboard/socials/'
    | '/dashboard/tags/'
    | '/dashboard/testimonials/'
    | '/dashboard/user-management/'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/blogs/$slug/'
    | '/dashboard/business-sectors/$slug/'
    | '/dashboard/client-projects/$slug/'
    | '/dashboard/contact-us/$id/'
    | '/dashboard/gallery/$id/'
    | '/dashboard/partners/$id/'
    | '/dashboard/products/$slug/'
    | '/dashboard/services/$slug/'
    | '/dashboard/testimonials/$id/'
    | '/dashboard/user-management/$userId/'
    | '/dashboard/vacancies/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForbiddenLazyRoute: typeof ForbiddenLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RateLimitLazyRoute: typeof RateLimitLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limit': {
      id: '/rate-limit'
      path: '/rate-limit'
      fullPath: '/rate-limit'
      preLoaderRoute: typeof RateLimitLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/schedule': {
      id: '/_site/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof SiteScheduleRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/dashboard/user-management/': {
      id: '/dashboard/user-management/'
      path: '/user-management'
      fullPath: '/dashboard/user-management'
      preLoaderRoute: typeof DashboardUserManagementIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/': {
      id: '/dashboard/testimonials/'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof DashboardTagsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/socials/': {
      id: '/dashboard/socials/'
      path: '/socials'
      fullPath: '/dashboard/socials'
      preLoaderRoute: typeof DashboardSocialsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/': {
      id: '/dashboard/partners/'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/organizational-structure/': {
      id: '/dashboard/organizational-structure/'
      path: '/organizational-structure'
      fullPath: '/dashboard/organizational-structure'
      preLoaderRoute: typeof DashboardOrganizationalStructureIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faqs/': {
      id: '/dashboard/faqs/'
      path: '/faqs'
      fullPath: '/dashboard/faqs'
      preLoaderRoute: typeof DashboardFaqsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/': {
      id: '/dashboard/contact-us/'
      path: '/contact-us'
      fullPath: '/dashboard/contact-us'
      preLoaderRoute: typeof DashboardContactUsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/': {
      id: '/dashboard/client-projects/'
      path: '/client-projects'
      fullPath: '/dashboard/client-projects'
      preLoaderRoute: typeof DashboardClientProjectsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/': {
      id: '/dashboard/vacancies/'
      path: '/vacancies'
      fullPath: '/dashboard/vacancies'
      preLoaderRoute: typeof DashboardVacanciesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/': {
      id: '/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/': {
      id: '/dashboard/gallery/'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/': {
      id: '/dashboard/business-sectors/'
      path: '/business-sectors'
      fullPath: '/dashboard/business-sectors'
      preLoaderRoute: typeof DashboardBusinessSectorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/': {
      id: '/dashboard/blogs/'
      path: '/blogs'
      fullPath: '/dashboard/blogs'
      preLoaderRoute: typeof DashboardBlogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_site/services/': {
      id: '/_site/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sectors/': {
      id: '/_site/sectors/'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SiteSectorsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/': {
      id: '/_site/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery/': {
      id: '/_site/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers/': {
      id: '/_site/careers/'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof SiteCareersIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blogs/': {
      id: '/_site/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof SiteBlogsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/dashboard/vacancies/create': {
      id: '/dashboard/vacancies/create'
      path: '/vacancies/create'
      fullPath: '/dashboard/vacancies/create'
      preLoaderRoute: typeof DashboardVacanciesCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/create': {
      id: '/dashboard/user-management/create'
      path: '/user-management/create'
      fullPath: '/dashboard/user-management/create'
      preLoaderRoute: typeof DashboardUserManagementCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/create': {
      id: '/dashboard/testimonials/create'
      path: '/testimonials/create'
      fullPath: '/dashboard/testimonials/create'
      preLoaderRoute: typeof DashboardTestimonialsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/create': {
      id: '/dashboard/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardProductsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/create': {
      id: '/dashboard/partners/create'
      path: '/partners/create'
      fullPath: '/dashboard/partners/create'
      preLoaderRoute: typeof DashboardPartnersCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/create': {
      id: '/dashboard/gallery/create'
      path: '/gallery/create'
      fullPath: '/dashboard/gallery/create'
      preLoaderRoute: typeof DashboardGalleryCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/create': {
      id: '/dashboard/contact-us/create'
      path: '/contact-us/create'
      fullPath: '/dashboard/contact-us/create'
      preLoaderRoute: typeof DashboardContactUsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/create': {
      id: '/dashboard/client-projects/create'
      path: '/client-projects/create'
      fullPath: '/dashboard/client-projects/create'
      preLoaderRoute: typeof DashboardClientProjectsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/create': {
      id: '/dashboard/blogs/create'
      path: '/blogs/create'
      fullPath: '/dashboard/blogs/create'
      preLoaderRoute: typeof DashboardBlogsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/create': {
      id: '/dashboard/services/create'
      path: '/services/create'
      fullPath: '/dashboard/services/create'
      preLoaderRoute: typeof DashboardServicesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/categories': {
      id: '/dashboard/gallery/categories'
      path: '/gallery/categories'
      fullPath: '/dashboard/gallery/categories'
      preLoaderRoute: typeof DashboardGalleryCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/create': {
      id: '/dashboard/business-sectors/create'
      path: '/business-sectors/create'
      fullPath: '/dashboard/business-sectors/create'
      preLoaderRoute: typeof DashboardBusinessSectorsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_site/services/$slug': {
      id: '/_site/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof SiteServicesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sectors/$slug': {
      id: '/_site/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SiteSectorsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/$slug': {
      id: '/_site/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof SiteProjectsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/careers/$slug': {
      id: '/_site/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof SiteCareersSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blogs/$slug': {
      id: '/_site/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof SiteBlogsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/dashboard/vacancies/$slug/': {
      id: '/dashboard/vacancies/$slug/'
      path: '/vacancies/$slug'
      fullPath: '/dashboard/vacancies/$slug'
      preLoaderRoute: typeof DashboardVacanciesSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/$userId/': {
      id: '/dashboard/user-management/$userId/'
      path: '/user-management/$userId'
      fullPath: '/dashboard/user-management/$userId'
      preLoaderRoute: typeof DashboardUserManagementUserIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/$id/': {
      id: '/dashboard/testimonials/$id/'
      path: '/testimonials/$id'
      fullPath: '/dashboard/testimonials/$id'
      preLoaderRoute: typeof DashboardTestimonialsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$slug/': {
      id: '/dashboard/services/$slug/'
      path: '/services/$slug'
      fullPath: '/dashboard/services/$slug'
      preLoaderRoute: typeof DashboardServicesSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$slug/': {
      id: '/dashboard/products/$slug/'
      path: '/products/$slug'
      fullPath: '/dashboard/products/$slug'
      preLoaderRoute: typeof DashboardProductsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/$id/': {
      id: '/dashboard/partners/$id/'
      path: '/partners/$id'
      fullPath: '/dashboard/partners/$id'
      preLoaderRoute: typeof DashboardPartnersIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/$id/': {
      id: '/dashboard/gallery/$id/'
      path: '/gallery/$id'
      fullPath: '/dashboard/gallery/$id'
      preLoaderRoute: typeof DashboardGalleryIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/$id/': {
      id: '/dashboard/contact-us/$id/'
      path: '/contact-us/$id'
      fullPath: '/dashboard/contact-us/$id'
      preLoaderRoute: typeof DashboardContactUsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/$slug/': {
      id: '/dashboard/client-projects/$slug/'
      path: '/client-projects/$slug'
      fullPath: '/dashboard/client-projects/$slug'
      preLoaderRoute: typeof DashboardClientProjectsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/$slug/': {
      id: '/dashboard/business-sectors/$slug/'
      path: '/business-sectors/$slug'
      fullPath: '/dashboard/business-sectors/$slug'
      preLoaderRoute: typeof DashboardBusinessSectorsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/$slug/': {
      id: '/dashboard/blogs/$slug/'
      path: '/blogs/$slug'
      fullPath: '/dashboard/blogs/$slug'
      preLoaderRoute: typeof DashboardBlogsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/$slug/edit': {
      id: '/dashboard/vacancies/$slug/edit'
      path: '/vacancies/$slug/edit'
      fullPath: '/dashboard/vacancies/$slug/edit'
      preLoaderRoute: typeof DashboardVacanciesSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/$slug/applications': {
      id: '/dashboard/vacancies/$slug/applications'
      path: '/vacancies/$slug/applications'
      fullPath: '/dashboard/vacancies/$slug/applications'
      preLoaderRoute: typeof DashboardVacanciesSlugApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/$userId/edit': {
      id: '/dashboard/user-management/$userId/edit'
      path: '/user-management/$userId/edit'
      fullPath: '/dashboard/user-management/$userId/edit'
      preLoaderRoute: typeof DashboardUserManagementUserIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/$id/edit': {
      id: '/dashboard/testimonials/$id/edit'
      path: '/testimonials/$id/edit'
      fullPath: '/dashboard/testimonials/$id/edit'
      preLoaderRoute: typeof DashboardTestimonialsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$slug/edit': {
      id: '/dashboard/services/$slug/edit'
      path: '/services/$slug/edit'
      fullPath: '/dashboard/services/$slug/edit'
      preLoaderRoute: typeof DashboardServicesSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$slug/edit': {
      id: '/dashboard/products/$slug/edit'
      path: '/products/$slug/edit'
      fullPath: '/dashboard/products/$slug/edit'
      preLoaderRoute: typeof DashboardProductsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/$id/edit': {
      id: '/dashboard/partners/$id/edit'
      path: '/partners/$id/edit'
      fullPath: '/dashboard/partners/$id/edit'
      preLoaderRoute: typeof DashboardPartnersIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/$id/edit': {
      id: '/dashboard/gallery/$id/edit'
      path: '/gallery/$id/edit'
      fullPath: '/dashboard/gallery/$id/edit'
      preLoaderRoute: typeof DashboardGalleryIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/$id/edit': {
      id: '/dashboard/contact-us/$id/edit'
      path: '/contact-us/$id/edit'
      fullPath: '/dashboard/contact-us/$id/edit'
      preLoaderRoute: typeof DashboardContactUsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/$slug/edit': {
      id: '/dashboard/client-projects/$slug/edit'
      path: '/client-projects/$slug/edit'
      fullPath: '/dashboard/client-projects/$slug/edit'
      preLoaderRoute: typeof DashboardClientProjectsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/$slug/edit': {
      id: '/dashboard/business-sectors/$slug/edit'
      path: '/business-sectors/$slug/edit'
      fullPath: '/dashboard/business-sectors/$slug/edit'
      preLoaderRoute: typeof DashboardBusinessSectorsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/$slug/edit': {
      id: '/dashboard/blogs/$slug/edit'
      path: '/blogs/$slug/edit'
      fullPath: '/dashboard/blogs/$slug/edit'
      preLoaderRoute: typeof DashboardBlogsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteScheduleRoute: typeof SiteScheduleRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogsSlugRoute: typeof SiteBlogsSlugRoute
  SiteCareersSlugRoute: typeof SiteCareersSlugRoute
  SiteProjectsSlugRoute: typeof SiteProjectsSlugRoute
  SiteSectorsSlugRoute: typeof SiteSectorsSlugRoute
  SiteServicesSlugRoute: typeof SiteServicesSlugRoute
  SiteBlogsIndexRoute: typeof SiteBlogsIndexRoute
  SiteCareersIndexRoute: typeof SiteCareersIndexRoute
  SiteGalleryIndexRoute: typeof SiteGalleryIndexRoute
  SiteProjectsIndexRoute: typeof SiteProjectsIndexRoute
  SiteSectorsIndexRoute: typeof SiteSectorsIndexRoute
  SiteServicesIndexRoute: typeof SiteServicesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteScheduleRoute: SiteScheduleRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogsSlugRoute: SiteBlogsSlugRoute,
  SiteCareersSlugRoute: SiteCareersSlugRoute,
  SiteProjectsSlugRoute: SiteProjectsSlugRoute,
  SiteSectorsSlugRoute: SiteSectorsSlugRoute,
  SiteServicesSlugRoute: SiteServicesSlugRoute,
  SiteBlogsIndexRoute: SiteBlogsIndexRoute,
  SiteCareersIndexRoute: SiteCareersIndexRoute,
  SiteGalleryIndexRoute: SiteGalleryIndexRoute,
  SiteProjectsIndexRoute: SiteProjectsIndexRoute,
  SiteSectorsIndexRoute: SiteSectorsIndexRoute,
  SiteServicesIndexRoute: SiteServicesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardBusinessSectorsCreateRoute: typeof DashboardBusinessSectorsCreateRoute
  DashboardGalleryCategoriesRoute: typeof DashboardGalleryCategoriesRoute
  DashboardServicesCreateRoute: typeof DashboardServicesCreateRoute
  DashboardBlogsCreateLazyRoute: typeof DashboardBlogsCreateLazyRoute
  DashboardClientProjectsCreateLazyRoute: typeof DashboardClientProjectsCreateLazyRoute
  DashboardContactUsCreateLazyRoute: typeof DashboardContactUsCreateLazyRoute
  DashboardGalleryCreateLazyRoute: typeof DashboardGalleryCreateLazyRoute
  DashboardPartnersCreateLazyRoute: typeof DashboardPartnersCreateLazyRoute
  DashboardProductsCreateLazyRoute: typeof DashboardProductsCreateLazyRoute
  DashboardTestimonialsCreateLazyRoute: typeof DashboardTestimonialsCreateLazyRoute
  DashboardUserManagementCreateLazyRoute: typeof DashboardUserManagementCreateLazyRoute
  DashboardVacanciesCreateLazyRoute: typeof DashboardVacanciesCreateLazyRoute
  DashboardBlogsIndexRoute: typeof DashboardBlogsIndexRoute
  DashboardBusinessSectorsIndexRoute: typeof DashboardBusinessSectorsIndexRoute
  DashboardGalleryIndexRoute: typeof DashboardGalleryIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardServicesIndexRoute: typeof DashboardServicesIndexRoute
  DashboardVacanciesIndexRoute: typeof DashboardVacanciesIndexRoute
  DashboardClientProjectsIndexLazyRoute: typeof DashboardClientProjectsIndexLazyRoute
  DashboardContactUsIndexLazyRoute: typeof DashboardContactUsIndexLazyRoute
  DashboardFaqsIndexLazyRoute: typeof DashboardFaqsIndexLazyRoute
  DashboardOrganizationalStructureIndexLazyRoute: typeof DashboardOrganizationalStructureIndexLazyRoute
  DashboardPartnersIndexLazyRoute: typeof DashboardPartnersIndexLazyRoute
  DashboardSocialsIndexLazyRoute: typeof DashboardSocialsIndexLazyRoute
  DashboardTagsIndexLazyRoute: typeof DashboardTagsIndexLazyRoute
  DashboardTestimonialsIndexLazyRoute: typeof DashboardTestimonialsIndexLazyRoute
  DashboardUserManagementIndexLazyRoute: typeof DashboardUserManagementIndexLazyRoute
  DashboardBlogsSlugEditRoute: typeof DashboardBlogsSlugEditRoute
  DashboardBusinessSectorsSlugEditRoute: typeof DashboardBusinessSectorsSlugEditRoute
  DashboardClientProjectsSlugEditRoute: typeof DashboardClientProjectsSlugEditRoute
  DashboardContactUsIdEditRoute: typeof DashboardContactUsIdEditRoute
  DashboardGalleryIdEditRoute: typeof DashboardGalleryIdEditRoute
  DashboardPartnersIdEditRoute: typeof DashboardPartnersIdEditRoute
  DashboardProductsSlugEditRoute: typeof DashboardProductsSlugEditRoute
  DashboardServicesSlugEditRoute: typeof DashboardServicesSlugEditRoute
  DashboardTestimonialsIdEditRoute: typeof DashboardTestimonialsIdEditRoute
  DashboardUserManagementUserIdEditRoute: typeof DashboardUserManagementUserIdEditRoute
  DashboardVacanciesSlugApplicationsRoute: typeof DashboardVacanciesSlugApplicationsRoute
  DashboardVacanciesSlugEditRoute: typeof DashboardVacanciesSlugEditRoute
  DashboardBlogsSlugIndexRoute: typeof DashboardBlogsSlugIndexRoute
  DashboardBusinessSectorsSlugIndexRoute: typeof DashboardBusinessSectorsSlugIndexRoute
  DashboardClientProjectsSlugIndexRoute: typeof DashboardClientProjectsSlugIndexRoute
  DashboardContactUsIdIndexRoute: typeof DashboardContactUsIdIndexRoute
  DashboardGalleryIdIndexRoute: typeof DashboardGalleryIdIndexRoute
  DashboardPartnersIdIndexRoute: typeof DashboardPartnersIdIndexRoute
  DashboardProductsSlugIndexRoute: typeof DashboardProductsSlugIndexRoute
  DashboardServicesSlugIndexRoute: typeof DashboardServicesSlugIndexRoute
  DashboardTestimonialsIdIndexRoute: typeof DashboardTestimonialsIdIndexRoute
  DashboardUserManagementUserIdIndexRoute: typeof DashboardUserManagementUserIdIndexRoute
  DashboardVacanciesSlugIndexRoute: typeof DashboardVacanciesSlugIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardBusinessSectorsCreateRoute: DashboardBusinessSectorsCreateRoute,
  DashboardGalleryCategoriesRoute: DashboardGalleryCategoriesRoute,
  DashboardServicesCreateRoute: DashboardServicesCreateRoute,
  DashboardBlogsCreateLazyRoute: DashboardBlogsCreateLazyRoute,
  DashboardClientProjectsCreateLazyRoute:
    DashboardClientProjectsCreateLazyRoute,
  DashboardContactUsCreateLazyRoute: DashboardContactUsCreateLazyRoute,
  DashboardGalleryCreateLazyRoute: DashboardGalleryCreateLazyRoute,
  DashboardPartnersCreateLazyRoute: DashboardPartnersCreateLazyRoute,
  DashboardProductsCreateLazyRoute: DashboardProductsCreateLazyRoute,
  DashboardTestimonialsCreateLazyRoute: DashboardTestimonialsCreateLazyRoute,
  DashboardUserManagementCreateLazyRoute:
    DashboardUserManagementCreateLazyRoute,
  DashboardVacanciesCreateLazyRoute: DashboardVacanciesCreateLazyRoute,
  DashboardBlogsIndexRoute: DashboardBlogsIndexRoute,
  DashboardBusinessSectorsIndexRoute: DashboardBusinessSectorsIndexRoute,
  DashboardGalleryIndexRoute: DashboardGalleryIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardServicesIndexRoute: DashboardServicesIndexRoute,
  DashboardVacanciesIndexRoute: DashboardVacanciesIndexRoute,
  DashboardClientProjectsIndexLazyRoute: DashboardClientProjectsIndexLazyRoute,
  DashboardContactUsIndexLazyRoute: DashboardContactUsIndexLazyRoute,
  DashboardFaqsIndexLazyRoute: DashboardFaqsIndexLazyRoute,
  DashboardOrganizationalStructureIndexLazyRoute:
    DashboardOrganizationalStructureIndexLazyRoute,
  DashboardPartnersIndexLazyRoute: DashboardPartnersIndexLazyRoute,
  DashboardSocialsIndexLazyRoute: DashboardSocialsIndexLazyRoute,
  DashboardTagsIndexLazyRoute: DashboardTagsIndexLazyRoute,
  DashboardTestimonialsIndexLazyRoute: DashboardTestimonialsIndexLazyRoute,
  DashboardUserManagementIndexLazyRoute: DashboardUserManagementIndexLazyRoute,
  DashboardBlogsSlugEditRoute: DashboardBlogsSlugEditRoute,
  DashboardBusinessSectorsSlugEditRoute: DashboardBusinessSectorsSlugEditRoute,
  DashboardClientProjectsSlugEditRoute: DashboardClientProjectsSlugEditRoute,
  DashboardContactUsIdEditRoute: DashboardContactUsIdEditRoute,
  DashboardGalleryIdEditRoute: DashboardGalleryIdEditRoute,
  DashboardPartnersIdEditRoute: DashboardPartnersIdEditRoute,
  DashboardProductsSlugEditRoute: DashboardProductsSlugEditRoute,
  DashboardServicesSlugEditRoute: DashboardServicesSlugEditRoute,
  DashboardTestimonialsIdEditRoute: DashboardTestimonialsIdEditRoute,
  DashboardUserManagementUserIdEditRoute:
    DashboardUserManagementUserIdEditRoute,
  DashboardVacanciesSlugApplicationsRoute:
    DashboardVacanciesSlugApplicationsRoute,
  DashboardVacanciesSlugEditRoute: DashboardVacanciesSlugEditRoute,
  DashboardBlogsSlugIndexRoute: DashboardBlogsSlugIndexRoute,
  DashboardBusinessSectorsSlugIndexRoute:
    DashboardBusinessSectorsSlugIndexRoute,
  DashboardClientProjectsSlugIndexRoute: DashboardClientProjectsSlugIndexRoute,
  DashboardContactUsIdIndexRoute: DashboardContactUsIdIndexRoute,
  DashboardGalleryIdIndexRoute: DashboardGalleryIdIndexRoute,
  DashboardPartnersIdIndexRoute: DashboardPartnersIdIndexRoute,
  DashboardProductsSlugIndexRoute: DashboardProductsSlugIndexRoute,
  DashboardServicesSlugIndexRoute: DashboardServicesSlugIndexRoute,
  DashboardTestimonialsIdIndexRoute: DashboardTestimonialsIdIndexRoute,
  DashboardUserManagementUserIdIndexRoute:
    DashboardUserManagementUserIdIndexRoute,
  DashboardVacanciesSlugIndexRoute: DashboardVacanciesSlugIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForbiddenLazyRoute: ForbiddenLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  RateLimitLazyRoute: RateLimitLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
